// Generated by OpenComposite's Reimpl/generate.py, do not hand modify as it will be overwritten!
static const char * IVROCSystem_Version = "IVROCSystem_001";
struct VR_IVROCSystem_FnTable
{
	uint64_t (OPENVR_FNTABLE_CALLTYPE* GetExtendedButtonStatus)();
};
